import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: {
    default: 'Recondition Hub ',
    template: '%s | Recondition Hub ',
  },
  description: 'Generated by create next app',
  openGraph: {
    title: 'Recondition Hub ',
    description: 'Generated by create next app',
  },
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
