import RegisterForm from '@/components/Form/RegisterForm';

export const metadata = {
  title: 'Register | Recondition Hub',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Register | Recondition Hub',
    description: 'Generated by create next app',
  },
};

const RegisterPage = () => {
  return <RegisterForm />;
};

export default RegisterPage;
