import LogInForm from '@/components/Form/LoginForm';

export const metadata = {
  title: 'Login | Recondition Hub',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Login | Recondition Hub',
    description: 'Generated by create next app',
  },
};

const LoginPage = () => {
  return <LogInForm />;
};

export default LoginPage;
