export const metadata = {
  title: 'Dashboard | Recondition Hub',
  description: 'Generated by create next app',
};

function DashboardLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export default DashboardLayout;
