export const metadata = {
  title: 'Our Vehicles | Recondition House',
  description: 'Generated by create next app',
};

const VehicleLayout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default VehicleLayout;
