import React from 'react';

import data from '@/data.json';
import { baseUrl } from '@/utils/constant';

export const metadata = {
  title: 'Terms and Conditions',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Terms and Conditions',
    description: 'Generated by create next app',
    url: baseUrl + '/terms',
  },
};

export default function TermsAndConditions() {
  return (
    <div className="bg-gray-100 py-10">
      <div className="container">
        <h1 className="mb-4 text-2xl font-bold">Terms and Conditions</h1>
        <div className="space-y-4">
          {data?.terms.map((section, index) => (
            <section key={index}>
              <h2 className="text-lg font-semibold">{section.title}</h2>
              <p className="text-sm text-gray-600">{section.content}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
