import React from 'react';
import { fetchData } from '@/utils/api-sercice';
import SectionHeading from '@/components/SectionHeading';
import FilterForm from '@/components/Form/FilterForm';
import { baseUrl } from '@/utils/constant';
import ThrottelData from '@/components/ThrottelData';

export const metadata = {
  title: 'Vehicles | Recondition Hub',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Vehicles | Recondition Hub',
    description: 'Generated by create next app',
    url: baseUrl + '/vehicles',
  },
};

const ProductsPage = async () => {
  const { data, error, loading } = await fetchData(`/vehicles/`, {
    method: 'GET',
  });

  if (!loading)
    return (
      <div className="min-h-[300px] py-10">
        <div className="container">
          <div className="flex items-center justify-between">
            <SectionHeading
              type="vehicles"
              title={'All Vehicles'}
              length={data?.count === 0 ? 0 : data?.count}
            />
            <div>
              <FilterForm />
            </div>
          </div>

          {!loading && data?.results && data.results.length > 0 ? (
            <ThrottelData url="/vehicles/" />
          ) : (
            <p className="mt-6 px-3 font-semibold text-gray-500">
              No Vehicles Found.
            </p>
          )}
        </div>
      </div>
    );
};

export default ProductsPage;
