import ProfileForm from '@/components/Form/ProfileForm';

export const metadata = {
  title: 'Profile | Recondition House',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Profile | Recondition House',
    description: 'Generated by create next app',
  },
};

const ProfilePage = () => {
  return (
    <>
      <ProfileForm />
    </>
  );
};

export default ProfilePage;
